apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  destination:
    name: victory4me
  project: default
  source:
    path: apps
    repoURL: https://github.com/techsysvbo/managed-argocd-lab # Update to your repo URL.
    targetRevision: HEAD
