apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/techsysvbo/managed-argocd-lab' # Update to match your fork.
    path: portal
    targetRevision: HEAD
  destination:
    namespace: default
    name: victory4me # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
